### PR TITLE
Nonlinear solver capability

### PR DESCRIPTION
**Pull request by aprokop**
Things are now in proper places. Now need to write IoC for nonlinear.

- [ ] Move some of the code from `test_nox.cpp` to `ModelEvaluator`
- [ ] Figure out why `SWIG_NO_NULL_DELETER_0` define is included *after* `ForModelEvaluator` in `fortrilinosFORTRAN_wrap.cxx`
- [ ] Better names of both functions and arguments
  Should be self-explanatory
- [ ] How does one cast `TpetraCrsMatrix` to `TpetraOperator`?
  We've never done that... is it possible?
- [ ] Can jacobian/preconditioner in `evaluate_jacobian`/`evaluate_preconditioner` be null?
  If yes, then should the interface be changed? Otherwise, it's unclear how to deal with that in Fortran if we cast.
- [ ] Should `self` argument be `intent(in)` or `intent(inout)`?
  ~The original `ModelEvaluator` functions are marked as `const`, so in IoC I originally used `intent(in)` for `self` argument. However, in the implementation details of `TpetraModelEvaluator1DFEM` it calls `allocate` which is incompatible to that.~ For now, I moved all `allocate` statement to `new`.
- [ ] `setup` in `TpetraModelEvaluator1DFEM` has only one argument, but is missing `f_map`.

### CODE REVIEW

**Comment by aprokop** [comment]
@tjfulle 

There are 3 functions in the model evaluator that are public but really should not be: `set_W_factory`, `create_W_op` and `getNominalValues`. It seems that we may need to move some of the code from `test_nox.cpp` inside the `ForTrilinos::ModelEvaluator`. I think we should integrate most of the following chunk:
```c++
  Stratimikos::DefaultLinearSolverBuilder builder;

  {
    auto p = Teuchos::rcpFromRef(plist->sublist("Linear Solver Settings"));

    std::string prec = p->get("Preconditioner Type", "None");
    if (prec == "None") {
      // Do nothing
    } else if (prec == "Ifpack2") {
      using Base = Thyra::PreconditionerFactoryBase<Scalar>;
      using Impl = Thyra::Ifpack2PreconditionerFactory<Tpetra::CrsMatrix<Scalar,LO,GO,Node>>;
      builder.setPreconditioningStrategyFactory(Teuchos::abstractFactoryStd<Base, Impl>(), "Ifpack2");
    } else {
      TEUCHOS_TEST_FOR_EXCEPTION(true, std::invalid_argument,
        "Preconditioner Type must be one of 'None', 'Ifpack2'")
    }
    builder.setParameterList(p);
  }

  RCP<Thyra::LinearOpWithSolveFactoryBase<Scalar>> lows_factory =
    builder.createLinearSolveStrategy("");

  model->set_W_factory(lows_factory);

  // Create the initial guess
  RCP<Thyra::VectorBase<Scalar>> initial_guess =
    model->getNominalValues().get_x()->clone_v();
  Thyra::V_S(initial_guess.ptr(),Teuchos::ScalarTraits<Scalar>::one());

  // Create the JFNK operator
  std::string jtype;
  RCP<NOX::Thyra::Group> nox_group;
  RCP<Thyra::PreconditionerBase<Scalar>> prec_op;
  RCP<Thyra::ModelEvaluator<Scalar>> thyra_model;
  RCP<NOX::Thyra::MatrixFreeJacobianOperator<Scalar>> jfnk_op;

  if (plist->isSublist("Jacobian Settings")) {
    auto jsettings = plist->sublist("Jacobian Settings");
    jtype = jsettings.get("Jacobian Type", "Analytic");
    if (jtype == "Analytic") {

      // Create the NOX::Thyra::Group
      nox_group = rcp(new NOX::Thyra::Group(*initial_guess, model,
                                            model->create_W_op(), lows_factory,
                                            Teuchos::null, Teuchos::null));

    } else {
      auto p = jsettings.sublist("Jacobian Types");
      if (jtype == "Matrix Free Newton") {
        auto jfnk_params = Teuchos::rcpFromRef(p.sublist(jtype));
        Teuchos::ParameterList print_params;
        jfnk_op = rcp(new NOX::Thyra::MatrixFreeJacobianOperator<Scalar>(print_params));
        jfnk_op->setParameterList(jfnk_params);
        jfnk_params->print(*out);

        // Wrap the model evaluator in a JFNK Model Evaluator
        thyra_model = rcp(new NOX::MatrixFreeModelEvaluatorDecorator<Scalar>(model));

        // Create the Preconditioner operator
        if (jsettings.get<bool>("Use Prec", false))
          prec_op = thyra_model->create_W_prec();

        // Create the NOX::Thyra::Group
        nox_group = rcp(new NOX::Thyra::Group(*initial_guess, thyra_model, jfnk_op,
                                              lows_factory, prec_op, Teuchos::null));

      }
    }
  } else {
    // Default to Analytic Jacobian
    nox_group = rcp(new NOX::Thyra::Group(*initial_guess, model,
                                          model->create_W_op(), lows_factory,
                                          Teuchos::null, Teuchos::null));
  }

  if (nox_group.is_null())
    TEUCHOS_TEST_FOR_EXCEPTION(true, std::invalid_argument, "Unkown Jacobian type " << jtype);
```

**Comment by tjfulle** [comment]
Thanks @aprokop!  I just saw this notification.  I’ll digest it tomorrow morning

**Comment by aprokop** [comment]
@tjfulle I pushed most of the IoC stuff in. It's very close to being able to compile, just a tiny bit off. But it should give you a good idea of how to use the new evaluator (see `test_nox.f90`). Now, we actually need a proper driver, as that file just contains the `1DFEM` module. I remember that at some point you had the driver, is that right?

**Comment by tjfulle** [comment]
I only have the C++ driver.  I can put together a Fortran driver pretty easily

**Comment by aprokop** [comment]
@tjfulle Tim, if I recall correctly, this ended up passing for JFNK. Can you recall if it passes for other methods, too? If yes, the only remaining issue would be the extra `release` function that cleans up both inherited class in Fortran and then calls the release on the base class. Do we have a path forward for that?

**Comment by aprokop** [comment]
Hmm, did not realize that `RCPNode` warnings actually fail CTest. Workound is to rely on `STANDARD_PASS_OUTPUT` Teuchos check.

**Pull request merged**
