### PR TITLE
ForTrilinos: adding simple interface

### PR DESCRIPTION
**Pull request by aprokop**
Partial #8

### CODE REVIEW

**Comment by aprokop** [comment]
Updated PR. Few things are still missing, but getting close. People can start looking at the interface.

**Comment by aprokop** [comment]
@sethrj I had to do a small tweak to `ParameterList` module in Fortran by making `ptr` public. Otherwise, how do we pass ParameterList in other modules inside Fortran proxies? Nota bene: I most likely miss something.

**Comment by maherou** [comment]
I like the pattern of the simple code.  As I read it, I notice that some of the design details can go a variety of ways.  Might it be worth vetting this code with some other Fortran app developers.  I am wondering if we can ID a few savvy Fortran users in the broader community to critique the design.

**Comment by aprokop** [comment]
@maherou This is definitely not the final design, and we will undoubtedly hit some real world limitations with it. What are the things that caught your eye?
And I agree that we should talk more to other folks.

I see some few obvious limitations of the current design:
1.  Its inability to work with multiple matrices simultaneously
2. Its strict requirement to deal with GIDs

**Comment by maherou** [comment]
The detail that I noticed is your item 1.  There is a bit too much magic for my tastes to see that the matrix is constructed but there is no object I can point to.  At the same time, I don't know the sensibilities of modern Fortran programmers, so I don't want to dismiss this approach without getting some input.

To me, having an object that I pass into the solver feels right, in addition to being able to have more than one linear problem, and similarly more than one solver instantiation available at one time.

**Comment by aprokop** [comment]
Ready for review.

**Comment by aprokop** [comment]
Updated PR to make `SimpleInterface` non-singleton, allowing solution of multiple systems simultaneously.

**Comment by aprokop** [comment]
Actually, it just seems to run, but also is buggy which needs fixing:

- Indices treatment: 1-based vs 0-based
- Need to add test to check solution

**Comment by aprokop** [comment]
Updated PR. Now I'm actually checking that the solutions are correct.

**Comment by aprokop** [comment]
Added inversion of control for linear operators. The task itself is tracked in #22. Now, the only thing that seems remaining is to provide IoC for preconditioners. This may take a bit more time.

**Comment by aprokop** [comment]
Hmm, the test fails though it runs fine for me. But, of course, I can reproduce it thanks to our container-based testing. I like it better and better every time I need to debug issues like this.

Anyways, I need to figure out what is the difference in Trilinos configuration between two.

**Comment by aprokop** [comment]
OK. Ready for review.

**Comment by youngmit** [comment]
I just looked through the standard, and it makes no guarantees about the order of evaluation of operands in logical statements. Therefore, it isn't safe to do something like:

    function bar(array) result(ret)
        real, intent(in) :: array(*)
        logical :: ret
        !...
    end subroutine
    real,pointer :: foo(:)
    !...
    if(associated(foo), bar(foo)) then
        !...
    end if

That said the test that raised the question is still fine, this is just for future reference.

**Comment by aprokop** [comment]
@sethrj Oh yes, you are right, I did want to change it to make MPI optional.

Yes, you are right about Belos and Ifpack2 being required for the provided input deck.

What changes are you referring to (SWIG automation)? I'd like to keep ierr as a parameter, but I could regenerate and then add it.

**Comment by sethrj** [comment]
The changes are in the `simple_seth` branch I pushed yesterday (you'll need the latest sethrj/swig/fortran branch).

Sure, ierr is more fortran-like, but unless you explicitly add it to your C interface, it's not something sustainable (since SWIG isn't able to automate adding an 'ierr' parameter). Will and I have a discussion about exception support [here](https://github.com/sethrj/swig/issues/10) and it would be good to decide on how to do it, and implement it, before we start hand-rolling a thousand different functions and their arguments.

**Comment by aprokop** [comment]
@sethrj I've updated the PR to address your comments:
- Added optional test dependencies
- Made MPI optional

**Comment by aprokop** [comment]
OK. I'm merging now, and then will incorporate bits and pieces from `simple_seth` branch.

**Pull request merged**
