### PR TITLE
added fortest.mod to install

### PR DESCRIPTION
**Pull request by mattbement**
To get an external build of the simple_eigen_handle test to work, this module file needs to be in the installed include directory.

### CODE REVIEW

**Comment by aprokop** [comment]
@mattbement Why do we need to install `fortest.mod`? It should only be used internally.

**Comment by mattbement** [comment]
Dunno - thought it was needed for comparisons of fortrilinos vectors/matrices etc.

**Comment by aprokop** [comment]
What do you mean for comparisons? In `fortest` module, we have setting up and tearing up modules, and some routines to compare results in Fortran arrays. This is not a general Trilinos module, only stuff required for tests.

Do you have a use case where a user needs that?

**Comment by mattbement** [comment]
I guess not - I was just thinking it contained an easy way to compare two matrices/vectors, which would be useful, but I didn't look in the module.

**Comment by aprokop** [comment]
@mattbement No. Comparing vectors needs to compute the norm of the difference. Comparing matrices is not really possible unless you fetch internal arrays.

**Pull request closed without merging**
