### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aprokop**

### CODE REVIEW

**Comment by kevans32** [comment]
I am not authorized or I would merge this. It needs a check? Really?

**Comment by aprokop** [comment]
@kevans32 Can you merge it now?

**Comment by kevans32** [comment]
No- (a) I thought one could merge automatically for a README change and (b) its says only collaborators with write access can merge. I was a collaborator just last week, no? Let me look...

**Comment by aprokop** [comment]
@kevans32 a) Nothing is merged automatically, and everything goes through testing. That's the law!
b) You are still the collaborator with a write access. Are you signed in?

**Comment by kevans32** [comment]
You just told me that an hour ago that readme changes needed only minimal testing, but obviously I misunderstood. We should test of course. As for (b) yes I am signed in.

**Comment by aprokop** [comment]
@kevans32 Try now.

**Pull request merged**
