### PR TITLE
WIP: Upgrade ForTrilinos and enable TpetraOperator derived type

### LINKED ISSUE #163: Implement automatic converters for ArrayView and ArrayRCP
Right now, I put a bunch of manual wrapper functions for those implementing essentially the same thing. Need to alias `ArrayView<T>` to `std::pair<T*,size_t>` which should reduce the amount of code.

### PR DESCRIPTION
**Pull request by sethrj**
This is an initial implementation of the callback functionality for the Tpetra operator. I've included a skeleton for a unit test that demonstrates its use. This MR supersedes #220 , most of #207 (aside from the int/logical type conversions), and the largest parts of #217.

Closes #163, #177, #185, #219

### CODE REVIEW

**Comment by sethrj** [comment]
@aprokop To get the builds to pass, unfortunately you'll have to remove the `-std=f2003` flag:
```

   call c_f_pointer(cptr=fself_ptr, fptr=handle)
                                        1
Error: TS 29113/TS 18508: Noninteroperable array FPTR at (1) to C_F_POINTER: Expression is a noninteroperable derived type
/scratch/source/trilinos/release/packages/ForTrilinos/src/tpetra/src/fortpetra.f90:6323:38:

 call c_f_pointer(cptr=fself_ptr, fptr=handle)
                                      1
Error: TS 29113/TS 18508: Noninteroperable array FPTR at (1) to C_F_POINTER: Expression is a noninteroperable derived type
```
This error is bogus, and is being fixed in the latest GCC, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84924 . But it'll be a while before any compiler sees that fix.

**Comment by aprokop** [comment]
Hmm, it explains the gcc failure. Flang compiles fine, but the failure of the test is probably due to missing functionality.

**Comment by aprokop** [comment]
I'd like to keep the flag to make sure we don't accidentally use any Fortran 2008 features. Ideally, the gcc folks would backport the patch into older compiler versions. But a) it unclear whether that would be done, and b) it may take a long time to get it to Ubuntu. I could switch to one of the recent gcc's once the patch is upstream. Should be easy with Spack. In the mean time, I probably need to follow @sethrj' advice and disable the flag. If I recall correctly, Flang just outright ignores that flag anyway.

**Comment by sethrj** [comment]
FWIW I'm continuing to build the SWIG test suite with `-std=f2003` so we should have at least some assurance of no F2008 features with that.

**Comment by sethrj** [comment]
All the useful parts of this have been incorporated into master.

**Pull request closed without merging**
